### PR TITLE
Travis-CI update to repo

### PR DESCRIPTION
**Pull request by kenman345**
This includes a few changes. 

First, this will require you to set up a Github token and add it to your repository variable settings as a private variable. instructions can be found here to make your token: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

The documentation on adding in that variable to travis is here: https://docs.travis-ci.com/user/deployment/pages/

Basically, you set a variable name `GITHUB_TOKEN` as a secure variable with the value of that token you generate. You do that within the travis-ci.org dashboard for your repository, in the "settings" area.

Instead of changing a space in one file and committing it each day, this will set the date to the travis-ci build server date when a cron job runs and then push that as a commit. That will cause the change you need. Since nothing uses that file, it doesnt really matter what the value is.

I also switched up your Travis build to use Stages. It gives us better control over cron jobs. It makes use of a rakefile to make sure we have locally reproducible scenarios as well. Rake Tasks. 

After merging this, if you run locally, you may wish to run `bundle install` and then `bundle update` to make sure you have no issues running your local environment.

### CODE REVIEW

**Comment by kenman345** [comment]
Also of note: When I changed the Travis-CI `.travis.yml` file, I changed you up to ruby 2.4.1. The reason being that its what the travis-ci build environment natively supports, so it will speed up the build process ever so slightly.

**Comment by kenman345** [comment]
So I noticed that the `date` in the frontmatter of your `_posts\weekly` files are a bit screwy. The first 3 weeks have the same date in the filename and in the frontmatter. This is all good. 

But starting from `2018-02-120wk4-guide.markdown` you have the frontmatter matching the last date of the week instead of the first date which is what the posts filename uses. This discrepancy meant I needed to include the following line to generate the pages with future dates included.
`'future' => true`
https://github.com/bibleplan/bibleplan.github.io/pull/5/files#diff-52c976fc38ed2b4e3b1192f8a8e24cffR11

The issue can be fixed by changing up that date field on the frontmatter. IF this is an issue because you rely on that date to be what you have it at, then we can go ahead and assign that date to a new variable in the frontmatter and transition the usage of that `date` field to the new variable we make.

**Comment by bibleplan** [comment]
The reason I set the Date of the weekly page to the end of the week is to make the weekly page on a later date than any of the daily page. For some reason I don't understand, if I set the Date to be Monday instead of Sunday, none of the daily pages will be included into the weekly page correctly. The daily pages are included as plain text, e.g. "### Questions" as is, instead of <h3>Questions</h3>.

Therefore, I kind of assume Github generate older pages first then more recent pages. The weekly page needs to have a later date to it will generated after all the daily pages are generated.

**Comment by kenman345** [comment]
I shall dig into that for you

**Pull request merged**
